ToyExchange/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^', include('apps.toys.urls', namespace='toys')),

]

apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
]

apps/login/models.py
from __future__ import unicode_literals

from django.db import models

class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.EmailField(max_length=255)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/login/views.py
from django.shortcuts import render, redirect
from .models import User
from ..toys.models import Toy, Image
from django.db.models import Count
from django.contrib import messages
import bcrypt

def index(request):
    context = {
        "toys": Toy.objects.all().order_by('-created_at'),
        "images": Image.objects.all().order_by('-id')[:10],
    }
    return render(request, 'login/index.html', context)

def register(request):
    if request.method == 'POST':
        alert = []
        validation = True
        check_user = User.objects.filter(username=request.POST['username'])
        if check_user:
            alert.append('The username already exists, please try another username.')
            validation = False
        if len(request.POST['first_name']) < 2 or len(request.POST['last_name']) < 2 or len(request.POST['username']) < 2:
            alert.append('Names and Usernames cannot be less than 2 letters.')
            validation = False
        if str.isalpha(str(request.POST['first_name'])) == False or str.isalpha(str(request.POST['last_name'])) == False :
            alert.append('Names cannot contain any numbers.')
            validation = False
        if len(request.POST['password']) < 1 or len(request.POST['confirm']) < 1 or len(request.POST['username']) < 1 or len(request.POST['email']) < 1 :
            alert.append('All fields are required and must not be blank.')
            validation = False
        if len(request.POST['password']) < 8:
            alert.append('Password should be 8 or more characters.')
            validation = False
        if request.POST['confirm'] != request.POST['password']:
            alert.append('Passwords do not match.')
            validation = False

        if validation == False:
            for i in range(0, len(alert)):
                messages.error(request, alert[i])
            return redirect('/')

        if validation == True:
            hashed = bcrypt.hashpw(request.POST['password'].encode(encoding="utf-8", errors="strict"), bcrypt.gensalt())
            user1 = User.objects.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'], username=request.POST['username'], password=hashed)
            request.session['user_id'] = user1.id
            request.session['first_name'] = user1.first_name
            request.session['username'] = user1.username
            context = {
                "toys": Toy.objects.all().order_by('-created_at'),
                "images": Image.objects.all(),
            }
            return render(request, 'toys/main.html', context)


def login(request):
    user1 = User.objects.filter(email=request.POST['email'])

    if not user1:
        messages.error(request, "The email you entered does not exist, please register!")
        return redirect('/')

    if bcrypt.checkpw(str(request.POST['password']), str(user1[0].password)):
        request.session['user_id'] = user1[0].id
        request.session['first_name'] = user1[0].first_name
        request.session['username'] = user1[0].username
        context = {
            "toys": Toy.objects.all().order_by('-created_at'),
            "images": Image.objects.all(),
        }
        return render(request, 'toys/main.html', context)

    else:
        messages.error(request, 'The email and password you entered do not match! Please try again.')
        return redirect('/')

def logout(request):
    request.session.clear()
    context = {
        "toys": Toy.objects.all().order_by('-created_at'),
        "images": Image.objects.all().order_by('-id')[:10],
    }
    return render(request, 'login/index.html', context)

apps/login/templates/login/index.html
<!-- Create by Jian Zhang @ Coding Dojo, on 02/26/2017 -->
<!DOCTYPE html>
<html>
    <head>
        {% load staticfiles %}
        <title>Toys X Change - Login</title>
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'login/css/materialize.min.css' %}">
        <link rel="stylesheet" href="{% static 'login/css/styles.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <style>

        </style>
    </head>

    <body>
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="{% static 'login/js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'login/js/java.js' %}"></script>

    <div id="wrapper">
        <nav>
          <div class="nav-wrapper blue-grey lighten-1 hoverable" id="header">
            <a href="#!" class="brand-logo left"><span id="logo">Toys X Change</span></a>
            <div id="login">
                <form action='{% url 'login:login' %}' method='post'>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col s6"></div>
                        <div class="col s2">
                          <div class="input-field inline">
                            <i class="material-icons prefix">email</i>
                            <input id="email" type="email" class="validate" name="email">
                            <label for="email" data-error="Not a valid email.." data-success="that's right..">Email</label>
                          </div>
                        </div>
                        <div class="col s2">
                          <div class="input-field inline">
                            <i class="material-icons prefix">vpn_key</i>
                            <input id="password" type="text" class="validate" name="password">
                            <label for="password">Password</label>
                          </div>
                        </div>
                        <div class="col s2" >
                            <button id="login_button" class="btn waves-effect blue" type="submit" name="action">Log in</button>
                        </div>
                    </div>
                </form>
            </div>

          </div>
        </nav>

        <main id="main">

          <div class="parallax-container">
              <div class="container">
                  <div class="row">
                      <div class="col l8 s12 white-text">
                          <h4 class="thin-text valign" id='main_txt'>Toys X Change is the revolutionary online marketplace for people to barter or sell unused toys.</h4>
                      </div>
                  </div>
              </div>
              <div class="parallax"><img class=" hoverable" src="{% static 'login/img/starwar.jpg' %}"></div>
          </div>

          <div id="messages" class="center-align">
              {% if messages %}
              <ul class="messages">
                  {% for message in messages %}
                  <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                  {% endfor %}
              </ul>
              {% endif %}
          </div>

        <div class="section light-blue lighten-5">
            <div class="container ">
                <div class="row">
                    <h2 class="center-align" id="service"> How It Works</h2>
                </div>
                <div class="row">
                    <div class="col m6 s12">
                        <div class="card medium light-blue accent-4 z-depth-3 hoverable">
                            <div class="card-content white-text">
                                <h3 class="center-align"><i class="large material-icons prefix">web</i></h3>
                                <div class="divider"></div>
                                <br />
                                <span class="card-title center-align">Barter Unused Toys</span>
                                <br />
                                <p>Helping parents to barter and exhange toys has been outgrown by their kids. Saw something your kids might like? Call or email the posting user, and arrange the swap. It's that easy!</p>
                            </div>
                        </div>
                    </div>
                    <!-- <div class="col m4 s12">
                        <div class="carousel">
                           {% for image in images %}
                           <a class="carousel-item" href="#one!"><img src="../../media/{{image.img}}"></a>
                           {% endfor %}
                        </div>
                    </div> -->
                    <div class="col m6 s12">
                        <div class="card medium light-blue accent-4 z-depth-3 hoverable">
                            <div class="card-content white-text">
                                <h3 class="center-align"><i class="large material-icons prefix">search</i></h3>
                                <div class="divider"></div>
                                <br />
                                <span class="card-title center-align">Discover New Hobbies </span>
                                <br />
                                <p>By exchanging unwanted toys to others, helping other kids to discover new way of having fun.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


          <!-- </div> -->
          <div class="parallax-container">
            <div class="parallax"><img src="{% static 'login/img/Lego.jpg' %}"></div>
          </div>


            <div class="section light-blue lighten-5">
              <div class="row container">
                    <h4 class="header center-align">Not A User Yet? Register Now!</h4>
                      <form class="col s12" action='{% url 'login:register' %}' method='post'>
                          {% csrf_token %}
                          <div class="row">
                              <div class="col s3">

                              </div>
                            <div class="input-field col s3">
                                <i class="material-icons prefix">account_circle</i>
                                <input name= "first_name" id="first_name" type="text" class="validate">
                                <label for="first">First Name</label>
                            </div>
                            <div class="input-field col s3">
                                <i class="material-icons prefix">perm_identity</i>
                                <input name= "last_name" id="last_name" type="text" class="validate">
                                <label for="last_name">Last Name</label>
                            </div>
                            <div class="col s3">

                            </div>
                          </div>
                          <div class="row">
                              <div class="col s3">

                              </div>
                            <div class="input-field col s3">
                                <i class="material-icons prefix">assignment_ind</i>
                                <input name= "username" id="username" type="text" class="validate">
                                <label for="username">Userame</label>
                            </div>
                            <div class="input-field col s3">
                                <i class="material-icons prefix">email</i>
                                <input name= "email" id="email" type="text" class="validate">
                                <label for="email">Email</label>
                            </div>
                            <div class="col s3">

                            </div>
                          </div>
                          <div class="row">
                              <div class="col s3">

                              </div>
                                <div class="input-field col s3">
                                    <i class="material-icons prefix">vpn_key</i>
                                    <input name= "password" placeholder="8 or more characters" id="password" type="text" class="validate">
                                    <label for="password">Password</label>
                                </div>
                                <div class="input-field col s3">
                                    <i class="material-icons prefix">vpn_key</i>
                                    <input name= "confirm" id="confirm" type="text" class="validate">
                                    <label for="confirm">Confirm PW</label>
                                </div>
                                <div class="col s3">

                                </div>
                          </div>
                          <div class="row">
                              <div class="col s3">

                              </div>
                              <div class="col s2">
                                  <button class="btn waves-effect blue" type="submit" name="action">Register
                                      <i class="material-icons right">input</i>
                                  </button>
                              </div>
                          </div>
                      </form>
                      <br />
                  </div>
              </div>
        </main>

        <div class="fixed-action-btn horizontal">
          <a class="btn-floating btn-large red">
            <i class="large material-icons">menu</i>
          </a>
          <ul>
            <li><a class="btn-floating green" href="#top"><i class="material-icons">publish</i></a></li>
          </ul>
        </div>


        <footer class="page-footer blue-grey lighten-1  hoverable" id="bottom">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Toys X Change</h5>
                <p class="grey-text text-lighten-4">Need to get rid of your kids old toys? Toys X change is the service that connects toys swappers together.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">How It Works</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Contacts</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Terms of Service</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2017 Copyright J.Z.  All Rights Reserved
            <a class="grey-text text-lighten-4 right" href="#!">Customer Service</a>
            </div>
          </div>
        </footer>
    </div>
    </body>
</html>