ToyExchange/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^', include('apps.toys.urls', namespace='toys')),

]

apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
]

apps/toys/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create$', views.create, name='create'),
    url(r'^goto$', views.goto, name='goto'),
    url(r'^goback$', views.goback, name='goback'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='delete'),
    url(r'^add/(?P<id>\d+)$', views.add, name='add'),
    url(r'^image/(?P<id>\d+)$', views.image, name='image'),
    url(r'^goto_edit/(?P<id>\d+)$', views.goto_edit, name='goto_edit'),
    url(r'^edit/(?P<id>\d+)$', views.edit, name='edit'),
    url(r'^user_all/(?P<id>\d+)$', views.user_all, name='user_all'),
    url(r'^category/(?P<category>\D+)$', views.category, name='category'),

]

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/toys/models.py
from __future__ import unicode_literals

from django.db import models
from ..login.models import User
from PIL import Image

class Toy(models.Model):
    name = models.CharField(max_length=45)
    msrp = models.CharField(max_length=45)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    age = models.CharField(max_length=45)
    category = models.CharField(max_length=45)
    condition = models.CharField(max_length=45)
    text = models.TextField(max_length=1000)
    zipcode = models.CharField(max_length=5)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, related_name='useruser')

class Image(models.Model):
    img = models.ImageField(upload_to='photo')
    toy = models.ForeignKey(Toy, related_name='toytoy')

apps/toys/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from .models import Toy, Image
from django.contrib import messages
from ..login.models import User

def index(request):
    user1 = User.objects.filter(user_id=request.session['user_id'])
    context = {
        "toys": Toy.objects.all().order_by('-created_at'),
        "images": Image.objects.all(),
    }
    return render(request, 'toys/main.html', context)

def create(request):
    alert = []
    validation = True
    if len(request.POST['name']) < 1 or len(request.POST['price']) < 1 or len(request.POST['zipcode']) < 1 or len(request.POST['text']) < 1 or request.POST['msrp'] == "" or request.POST['age'] == "" or request.POST['category'] == "" or request.POST['condition'] == "":
        alert.append('All fields are required and must not be blank.')
        validation = False
    if len(request.POST['zipcode']) != 5:
        alert.append('Please use 5 digits zipcode.')
        validation = False

    if validation == False:
        for i in range(0, len(alert)):
            messages.error(request, alert[i])
        return render(request, 'toys/new.html')

    else:
        Toy.objects.create(user_id=request.session.get('user_id'), name=request.POST['name'], zipcode=request.POST['zipcode'],price=request.POST['price'], msrp=request.POST['msrp'], age=request.POST['age'], category=request.POST['category'], condition=request.POST['condition'], text=request.POST['text'])
        context = {
            "toys": Toy.objects.all().order_by('-created_at'),
            "images": Image.objects.all(),
        }
        return render(request,'toys/main.html', context)

def goto(request):
    return render(request, 'toys/new.html')

def goback(request):
    context = {
        "toys": Toy.objects.all().order_by('-created_at'),
        "images": Image.objects.all(),
    }
    return render(request,'toys/main.html', context)

def delete(request, id):
    Toy.objects.filter(id=id).delete()
    context = {
        "toys": Toy.objects.all().order_by('-created_at'),
        "images": Image.objects.all(),
    }
    return render(request,'toys/main.html', context)

def add(request, id):
    context = {
        "id" : id
    }
    return render(request,'toys/add_image.html', context)

def image(request, id):
    # alert = []
    # if request.POST['image'] == None:
    #     alert.append('Oops, seems that you forget to select a toy photo, try again.')
    #
    # else:
        Image.objects.create(img=request.FILES['image'], toy_id=id)
        context = {
            "toys": Toy.objects.all().order_by('-created_at'),
            "images": Image.objects.all(),
        }
        return render(request,'toys/main.html', context)

def goto_edit(request, id):
    request.session['id'] = id
    context = {
        "toy": Toy.objects.filter(id=id),
    }
    return render(request,'toys/edit.html', context)

def edit(request, id):
    alert = []
    validation = True
    if len(request.POST['name']) < 1 or len(request.POST['price']) < 1 or len(request.POST['zipcode']) < 1 or len(request.POST['text']) < 1 or request.POST['msrp'] == "" or request.POST['age'] == "" or request.POST['category'] == "" or request.POST['condition'] == "":
        alert.append('All fields are required and must not be blank.')
        validation = False
    if len(request.POST['zipcode']) != 5:
        alert.append('Please use 5 digits zipcode.')
        validation = False

    if validation == False:
        for i in range(0, len(alert)):
            messages.error(request, alert[i])
        context = {
            "toy": Toy.objects.filter(id=request.session['id']),
        }
        return render(request, 'toys/edit.html', context)

    else:
        Toy.objects.filter(id=id).update(name=request.POST['name'], zipcode=request.POST['zipcode'],price=request.POST['price'], msrp=request.POST['msrp'], age=request.POST['age'], category=request.POST['category'], condition=request.POST['condition'], text=request.POST['text'])
        context = {
            "toys": Toy.objects.all().order_by('-updated_at'),
            "images": Image.objects.all(),
        }
        return render(request,'toys/main.html', context)

def user_all(request, id):
    context = {
        "toys": Toy.objects.filter(user_id=id).order_by('-created_at'),
        "images": Image.objects.all(),
        "user": User.objects.filter(id=id),

    }
    return render(request,'toys/user_all.html', context)

def category(request, category):
    request.session['category'] = category
    context = {
        "toys": Toy.objects.filter(category=category).order_by('-created_at'),
        "images": Image.objects.all(),
    }
    return render(request,'toys/category.html', context)

apps/toys/templates/toys/category.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Toys X Change - All Toys For This User</title>
        {% load staticfiles %}
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'login/css/materialize.min.css' %}">
        <link rel="stylesheet" href="{% static 'toys/css/toys.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <style>
            #toy_name{
                color:black;
                font-size: 35px;
            }
            .txt{
                font-size: 25px;
            }
            .item{
                color:black;
            }
        </style>
    </head>

    <body>
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="{% static 'login/js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'toys/js/toys.js' %}"></script>
        <div id="wrapper">
            <a name="top"></a>
            <nav>
              <div class="nav-wrapper blue-grey lighten-1 hoverable" id="header">
                <a href="#!" class="brand-logo left"><span id="logo">Toys X Change</span></a>
                <div id="logout">
                    <div class="row">
                        <div class="col s2 right" >
                            <button id="logout_button" class="btn waves-effect red" type="submit" name="action"><a href='{%  url 'login:logout' %}'>Logout</a></button>
                        </div>
                        <div class="col s2 right" >
                              <a class='dropdown-button btn blue' href='#' data-activates='dropdown1'>Toys by Category</a>
                              <ul id='dropdown1' class='dropdown-content'>
                                <li><a href="{% url 'toys:category' category='Action Figures' %}">Action Figures</a></li>
                                <li><a href="{% url 'toys:category' category='Video Games' %}">Video Games</a></li>
                                <li><a href="{% url 'toys:category' category='Legos' %}">Legos</a></li>
                                <li><a href="{% url 'toys:category' category='Dolls' %}">Dolls</a></li>
                                <li><a href="{% url 'toys:category' category='Cars' %}">Cars</a></li>
                                <li><a href="{% url 'toys:category' category='Bikes' %}">Bikes</a></li>
                              </ul>
                        </div>
                    </div>
                </div>

              </div>
            </nav>
            <h3 class="center" id="greet">All the posts for <i>"{{request.session.category}}"</i> Category.</h3>
            <div id="new">
                <div class="row">
                    <div class="col s2 right">
                        <a class="waves-effect blue btn" href='{% url 'toys:goback' %}'><i class="material-icons right">reply</i>Go Back</a>
                    </div>
                </div>
            </div>


       <div class="row">
               {% for toy in toys %}
           <div class="col s12 m6">
             <div class="card light-blue hoverable">
               <div class="card-content white-text">
                 <h4 id="toy_name" class="card-title center">Toy Name: <i>{{toy.name}}</i></h4>
                 <div class="row">
                     <div class="col s5" >
                         <h3 class="card-title black-text">Seller Name: {{toy.user.first_name}}</h3>
                     </div>
                 </div>
                 <div class="divider"></div>
                 <br />
                 {% if request.session.user_id == toy.user_id %}
                 <a class="btn-floating waves-effect waves-light yellow right" href='{% url 'toys:goto_edit' id=toy.id %}'><i class="material-icons">mode_edit</i>Edit</a>
                 <a class="btn-floating fab waves-effect waves-light green right" href='{% url 'toys:add' id=toy.id %}'><i class="material-icons">add</i>Add Photo</a>
                 <a class="btn-floating fab waves-effect waves-light red right" href='{% url 'toys:delete' id=toy.id %}'><i class="material-icons">delete</i>Delete</a>
                 {% endif %}
                 <p class="txt"><span class="item">[ Toy ID ]:</span> &nbsp;{{toy.id}}</p>
                 <p class="txt"><span class="item">[ Original MSRP ]:</span> &nbsp;{{toy.msrp}}</p>
                 <p class="txt"><span class="item">[ Asking Price ]:</span> &nbsp;${{toy.price}}</p>
                 <p class="txt"><span class="item">[ For Age Group ]:</span> &nbsp;{{toy.age}}</p>
                 <p class="txt"><span class="item">[ Category ]:</span> &nbsp;{{toy.category}}</p>
                 <p class="txt"><span class="item">[ Condition ]</span>: &nbsp;{{toy.condition}}</p>
                 <p class="txt"><span class="item">[ Comments ]:</span> &nbsp;{{toy.text}}</p>
                 <p class="txt"><span class="item">[ Contact This User by Email ]:</span> &nbsp;<u>{{toy.user.email}}</u></p>
                 <p class="txt"><span class="item">[ Posted at ]:</span> &nbsp;{{toy.created_at}}</p>
                 <br/>
                 {% for image in images %}
                 {% if image.toy_id == toy.id %}
                 <div class="divider"></div>
                 <br/>
                 <img src="../../media/{{image.img}}" />
                 {% endif %}
                 {% endfor %}
                 <br/>
                 <div class="divider"></div>
                 <br/>
                 <p class="txt">This toy is located at zipcode: {{toy.zipcode}}.</p>
                 <br/>
                 <img src="https://maps.googleapis.com/maps/api/staticmap?center={{toy.zipcode}}&zoom=12&size=600x400&markers=color:red%7C{{toy.zipcode}}&key=AIzaSyDFnW8QKPeWixw3nC4w2vkdRWZ4v3wQDfY" />


             </br/>
               </div>
             </div>
           </div>
           {% endfor %}
       </div>


       <div class="fixed-action-btn horizontal">
         <a class="btn-floating btn-large red">
           <i class="large material-icons">menu</i>
         </a>
         <ul>
           <li><a class="btn-floating red" href='{% url 'login:logout' %}'><i class="material-icons">exit_to_app</i></a></li>
           <li><a class="btn-floating yellow darken-1" href='{% url 'toys:goback' %}'><i class="material-icons">reply</i></a></li>
           <li><a class="btn-floating blue" href='{% url 'toys:goto' %}'><i class="material-icons">mode_edit</i></a></li>
           <li><a class="btn-floating green" href="#top"><i class="material-icons">publish</i></a></li>
         </ul>
       </div>

            <footer class="page-footer blue-grey lighten-1  hoverable" id="bottom">
              <div class="container">
                <div class="row">
                  <div class="col l6 s12">
                    <h5 class="white-text">Toys X Change</h5>
                    <p class="grey-text text-lighten-4">Need to get rid of your kids old toys? Toys X change is the service that connects toys swappers together.</p>
                  </div>
                  <div class="col l4 offset-l2 s12">
                    <h5 class="white-text">Links</h5>
                    <ul>
                      <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
                      <li><a class="grey-text text-lighten-3" href="#!">How It Works</a></li>
                      <li><a class="grey-text text-lighten-3" href="#!">Contacts</a></li>
                      <li><a class="grey-text text-lighten-3" href="#!">Terms of Service</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="footer-copyright">
                <div class="container">
                © 2017 Copyright J.Z.  All Rights Reserved
                <a class="grey-text text-lighten-4 right" href="#!">Customer Service</a>
                </div>
              </div>
            </footer>
        </div>
    </body>
</html>

apps/toys/templates/toys/main.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Toys X Change - Main Page</title>
        {% load staticfiles %}
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'login/css/materialize.min.css' %}">
        <link rel="stylesheet" href="{% static 'toys/css/toys.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <style>
            #toy_name{
                color:black;
                font-size: 35px;
            }
            .txt{
                font-size: 25px;
            }
            .item{
                color:black;
            }
        </style>
    </head>

    <body>
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="{% static 'login/js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'toys/js/toys.js' %}"></script>
        <div id="wrapper">
            <a name="top"></a>
            <nav>
              <div class="nav-wrapper blue-grey lighten-1 hoverable" id="header">
                <a href="#!" class="brand-logo left"><span id="logo">Toys X Change</span></a>
                <div id="logout">
                    <div class="row">
                        <div class="col s2 right" >
                            <button id="logout_button" class="btn waves-effect red" type="submit" name="action"><a href='{%  url 'login:logout' %}'>Logout</a></button>
                        </div>
                        <div class="col s2 right" >
                              <a class='dropdown-button btn blue' href='#' data-activates='dropdown1'>Toys by Category</a>
                              <ul id='dropdown1' class='dropdown-content'>
                                <li><a href="{% url 'toys:category' category='Action Figures' %}">Action Figures</a></li>
                                <li><a href="{% url 'toys:category' category='Video Games' %}">Video Games</a></li>
                                <li><a href="{% url 'toys:category' category='Legos' %}">Legos</a></li>
                                <li><a href="{% url 'toys:category' category='Dolls' %}">Dolls</a></li>
                                <li><a href="{% url 'toys:category' category='Cars' %}">Cars</a></li>
                                <li><a href="{% url 'toys:category' category='Bikes' %}">Bikes</a></li>
                              </ul>
                        </div>
                    </div>
                </div>

              </div>
            </nav>
            <h3 class="center" id="greet">Hello, <i>{{request.session.first_name}}</i> ! Welcome to the posting board!</h3>
            <br />
            <div id="new">
                <div class="row">
                    <div class="col s4" >

                    </div>
                    <div class="col s2" >
                        <a class="waves-effect blue btn" href='{% url 'toys:goto' %}'>Create A New Post</a>
                    </div>
                    <div class="col s2" >
                        <a class="waves-effect orange darken-1 btn" href='{% url 'toys:user_all' id=request.session.user_id %}'>See My Own Posts</a>
                    </div>
                </div>
            </div>


       <div class="row">
               {% for toy in toys %}
           <div class="col s12 m6">
             <div class="card light-blue hoverable">
               <div class="card-content white-text">
                   <h3 id="toy_name" class="card-title center-align">Toy Name: <i>{{toy.name}}</i></h3>
                   <br />
                   <div class="row">
                       <div class="col s5" >
                           <h3 class="card-title black-text">Seller Name: {{toy.user.first_name}}</h3>
                       </div>
                       <div class="col s2 right" >
                           <a class="waves-effect orange darken-1 btn" href='{% url 'toys:user_all' id=toy.user_id %}'>View</a>
                       </div>
                       <div class="col s3 right" >
                           <p>Click this button to view other posts of this user.</p>
                       </div>
                 </div>
                 <div class="divider"></div>
                 <br />
                 {% if request.session.user_id == toy.user_id %}
                 <a class="btn-floating waves-effect waves-light yellow right" href='{% url 'toys:goto_edit' id=toy.id %}'><i class="material-icons">mode_edit</i>Edit</a>
                 <a class="btn-floating fab waves-effect waves-light green right" href='{% url 'toys:add' id=toy.id %}'><i class="material-icons">add</i>Add Photo</a>
                 <a class="btn-floating fab waves-effect waves-light red right" href='{% url 'toys:delete' id=toy.id %}'><i class="material-icons">delete</i>Delete</a>
                 {% endif %}
                 <p class="txt"><span class="item">[ Toy ID ]:</span> &nbsp;{{toy.id}}</p>
                 <p class="txt"><span class="item">[ Original MSRP ]:</span> &nbsp;{{toy.msrp}}</p>
                 <p class="txt"><span class="item">[ Asking Price ]:</span> &nbsp;${{toy.price}}</p>
                 <p class="txt"><span class="item">[ For Age Group ]:</span> &nbsp;{{toy.age}}</p>
                 <p class="txt"><span class="item">[ Category ]:</span> &nbsp;{{toy.category}}</p>
                 <p class="txt"><span class="item">[ Condition ]:</span> &nbsp;{{toy.condition}}</p>
                 <p class="txt"><span class="item">[ Comments ]:</span> &nbsp;{{toy.text}}</p>
                 <p class="txt"><span class="item">[ Contact This User by Email ]:</span> &nbsp;<u>{{toy.user.email}}</u></p>
                 <p class="txt"><span class="item">[ Posted at ]:</span> &nbsp;{{toy.created_at}}</p>
                 <br/>
                 {% for image in images %}
                 {% if image.toy_id == toy.id %}
                 <div class="divider"></div>
                 <br/>
                 <img src="../media/{{image.img}}" />
                 {% endif %}
                 {% endfor %}
                 <br/>
                 <div class="divider"></div>
                 <br/>
                 <p class="txt">This toy is located at zipcode: {{toy.zipcode}}.</p>
                 <br/>
                 <img src="https://maps.googleapis.com/maps/api/staticmap?center={{toy.zipcode}}&zoom=12&size=600x400&markers=color:red%7C{{toy.zipcode}}&key=AIzaSyDFnW8QKPeWixw3nC4w2vkdRWZ4v3wQDfY" />
                </br/>
               </div>
             </div>
           </div>
           {% endfor %}
       </div>


       <div class="fixed-action-btn horizontal">
         <a class="btn-floating btn-large red">
           <i class="large material-icons">menu</i>
         </a>
         <ul>
           <li><a class="btn-floating red" href='{% url 'login:logout' %}'><i class="material-icons">exit_to_app</i></a></li>
           <li><a class="btn-floating yellow darken-1" href='{% url 'toys:goback' %}'><i class="material-icons">reply</i></a></li>
           <li><a class="btn-floating blue" href='{% url 'toys:goto' %}'><i class="material-icons">mode_edit</i></a></li>
           <li><a class="btn-floating green" href="#top"><i class="material-icons">publish</i></a></li>
         </ul>
       </div>

            <footer class="page-footer blue-grey lighten-1  hoverable" id="bottom">
              <div class="container">
                <div class="row">
                  <div class="col l6 s12">
                    <h5 class="white-text">Toys X Change</h5>
                    <p class="grey-text text-lighten-4">Need to get rid of your kids old toys? Toys X change is the service that connects toys swappers together.</p>
                  </div>
                  <div class="col l4 offset-l2 s12">
                    <h5 class="white-text">Links</h5>
                    <ul>
                      <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
                      <li><a class="grey-text text-lighten-3" href="#!">How It Works</a></li>
                      <li><a class="grey-text text-lighten-3" href="#!">Contacts</a></li>
                      <li><a class="grey-text text-lighten-3" href="#!">Terms of Service</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="footer-copyright">
                <div class="container">
                © 2017 Copyright J.Z.  All Rights Reserved
                <a class="grey-text text-lighten-4 right" href="#!">Customer Service</a>
                </div>
              </div>
            </footer>
        </div>
    </body>
</html>

apps/toys/templates/toys/user_all.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Toys X Change - All Toys For This User</title>
        {% load staticfiles %}
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'login/css/materialize.min.css' %}">
        <link rel="stylesheet" href="{% static 'toys/css/toys.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <style>
            #toy_name{
                color:black;
                font-size: 35px;
            }
            .txt{
                font-size: 25px;
            }
            .item{
                color:black;
            }
        </style>
    </head>

    <body>
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="{% static 'login/js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'toys/js/toys.js' %}"></script>
        <div id="wrapper">
            <a name="top"></a>
            <nav>
              <div class="nav-wrapper blue-grey lighten-1 hoverable" id="header">
                <a href="#!" class="brand-logo left"><span id="logo">Toys X Change</span></a>
                <div id="logout">
                    <div class="row">
                        <div class="col s2 right" >
                            <button id="logout_button" class="btn waves-effect blue" type="submit" name="action"><a href='{%  url 'login:logout' %}'>Logout</a></button>
                        </div>
                    </div>
                </div>

              </div>
            </nav>
            {% for user in user %}
            <h3 class="center" id="greet"><i>{{request.session.first_name}}</i>, you are viewing all the post for user - <u>"{{user.first_name}}"</u></h3>
            {% endfor %}
            <div id="new">
                <div class="row">
                    <div class="col s2 right">
                        <a class="waves-effect blue btn" href='{% url 'toys:goback' %}'><i class="material-icons right">reply</i>Go Back</a>
                    </div>
                </div>
            </div>


       <div class="row">
               {% for toy in toys %}
           <div class="col s12 m6">
             <div class="card light-blue hoverable">
               <div class="card-content white-text">
                 <h4 id="toy_name" class="card-title center">Toy Name: <i>{{toy.name}}</i></h4>
                 <br />
                 <div class="divider"></div>
                 <br />
                 {% if request.session.user_id == toy.user_id %}
                 <a class="btn-floating waves-effect waves-light yellow right" href='{% url 'toys:goto_edit' id=toy.id %}'><i class="material-icons">mode_edit</i>Edit</a>
                 <a class="btn-floating fab waves-effect waves-light green right" href='{% url 'toys:add' id=toy.id %}'><i class="material-icons">add</i>Add Photo</a>
                 <a class="btn-floating fab waves-effect waves-light red right" href='{% url 'toys:delete' id=toy.id %}'><i class="material-icons">delete</i>Delete</a>
                 {% endif %}
                 <p class="txt"><span class="item">[ Toy ID ]:</span> &nbsp;{{toy.id}}</p>
                 <p class="txt"><span class="item">[ Original MSRP ]:</span> &nbsp;{{toy.msrp}}</p>
                 <p class="txt"><span class="item">[ Asking Price ]:</span> &nbsp;${{toy.price}}</p>
                 <p class="txt"><span class="item">[ For Age Group ]:</span> &nbsp;{{toy.age}}</p>
                 <p class="txt"><span class="item">[ Category ]:</span> &nbsp;{{toy.category}}</p>
                 <p class="txt"><span class="item">[ Condition ]</span>: &nbsp;{{toy.condition}}</p>
                 <p class="txt"><span class="item">[ Comments ]:</span> &nbsp;{{toy.text}}</p>
                 <p class="txt"><span class="item">[ Contact This User by Email ]:</span> &nbsp;<u>{{toy.user.email}}</u></p>
                 <p class="txt"><span class="item">[ Posted at ]:</span> &nbsp;{{toy.created_at}}</p>
                 <br/>
                 {% for image in images %}
                 {% if image.toy_id == toy.id %}
                 <div class="divider"></div>
                 <br/>
                 <img src="../../media/{{image.img}}" />
                 {% endif %}
                 {% endfor %}
                 <br/>
                 <div class="divider"></div>
                 <br/>
                 <p class="txt">This toy is located at zipcode: {{toy.zipcode}}.</p>
                 <br/>
                 <img src="https://maps.googleapis.com/maps/api/staticmap?center={{toy.zipcode}}&zoom=12&size=600x400&markers=color:red%7C{{toy.zipcode}}&key=AIzaSyDFnW8QKPeWixw3nC4w2vkdRWZ4v3wQDfY" />


             </br/>
               </div>
             </div>
           </div>
           {% endfor %}
       </div>


       <div class="fixed-action-btn horizontal">
         <a class="btn-floating btn-large red">
           <i class="large material-icons">menu</i>
         </a>
         <ul>
           <li><a class="btn-floating red" href='{% url 'login:logout' %}'><i class="material-icons">exit_to_app</i></a></li>
           <li><a class="btn-floating yellow darken-1" href='{% url 'toys:goback' %}'><i class="material-icons">reply</i></a></li>
           <li><a class="btn-floating blue" href='{% url 'toys:goto' %}'><i class="material-icons">mode_edit</i></a></li>
           <li><a class="btn-floating green" href="#top"><i class="material-icons">publish</i></a></li>
         </ul>
       </div>

            <footer class="page-footer blue-grey lighten-1  hoverable" id="bottom">
              <div class="container">
                <div class="row">
                  <div class="col l6 s12">
                    <h5 class="white-text">Toys X Change</h5>
                    <p class="grey-text text-lighten-4">Need to get rid of your kids old toys? Toys X change is the service that connects toys swappers together.</p>
                  </div>
                  <div class="col l4 offset-l2 s12">
                    <h5 class="white-text">Links</h5>
                    <ul>
                      <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
                      <li><a class="grey-text text-lighten-3" href="#!">How It Works</a></li>
                      <li><a class="grey-text text-lighten-3" href="#!">Contacts</a></li>
                      <li><a class="grey-text text-lighten-3" href="#!">Terms of Service</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="footer-copyright">
                <div class="container">
                © 2017 Copyright J.Z.  All Rights Reserved
                <a class="grey-text text-lighten-4 right" href="#!">Customer Service</a>
                </div>
              </div>
            </footer>
        </div>
    </body>
</html>